// Contatos reais podem ser configurados aqui, sem alterar a interface.
const CONTACT = {whatsapp:'https://wa.me/5511972521502', instagram:'https://www.instagram.com/commo.arquitetura?stkn=YW5jbnoyZHZjNmdu'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const hero=$('.journey'),frames=$$('.frame'),copy=$('.hero-copy'),exit=$('.hero-exit'),header=$('#header'),bar=$('.progress span'),heroBottom=$('.hero-bottom');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
document.documentElement.classList.add('js-ready');
const revealItems=$$('[data-reveal]');
if('IntersectionObserver' in window && !reduced.matches){const revealObserver=new IntersectionObserver(items=>items.forEach(item=>{if(item.isIntersecting){item.target.classList.add('is-in-view');revealObserver.unobserve(item.target)}}),{threshold:.08,rootMargin:'0px 0px -6% 0px'});revealItems.forEach(item=>revealObserver.observe(item))}else revealItems.forEach(item=>item.classList.add('is-in-view'));
const parallaxImages=$$('[data-parallax] .folio-image img');
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));const smooth=v=>v*v*(3-2*v);
let pending=false;
function paint(){pending=false;const rect=hero.getBoundingClientRect(),h=innerHeight,p=clamp(-rect.top/Math.max(1,hero.offsetHeight-h));header.classList.toggle('solid',rect.bottom<85);if(reduced.matches)return;const sequence=p*3.65;const isMobile=innerWidth<768;frames.forEach((frame,i)=>{let alpha=i===0?1:smooth(clamp((sequence-i+.65)/.65));frame.style.opacity=alpha;const local=clamp(sequence-i+.45);const scale=1+local*(isMobile?.008:.055);const drift=isMobile?(local-.5)*-.08:(local-.5)*-.5;frame.style.transform=`scale(${scale}) translate3d(${drift}%,0,0)`;});const copyIn=smooth(clamp((p-.83)/.07));const copyOut=smooth(clamp((p-.965)/.035));copy.style.opacity=copyIn*(1-copyOut);copy.style.transform='translateY('+((1-copyIn)*28-copyOut*12)+'px)';const cueOut=smooth(clamp((p-.04)/.2));heroBottom.style.opacity=1-cueOut;heroBottom.style.transform='translateY('+(cueOut*12)+'px)';exit.style.opacity=smooth(clamp((p-.965)/.035));bar.style.transform='scaleX('+p+')';if(innerWidth>=768){parallaxImages.forEach(img=>{const r=img.closest('[data-parallax]').getBoundingClientRect();const offset=clamp((innerHeight/2-(r.top+r.height/2))/innerHeight*11,-7,7);img.style.setProperty('--parallax-offset',`${offset}px`)})}}
function schedule(){if(!pending){pending=true;requestAnimationFrame(paint)}}addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);reduced.addEventListener('change',schedule);paint();
// Decode each frame ahead of its entrance; all layers retain a painted backdrop.
async function decodeFrames(){for(const picture of frames){const img=picture.querySelector("img");try{await img.decode()}catch{}}}decodeFrames();
const menu=$('.menu-toggle');function closeMenu(){header.classList.remove('menu-open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Abrir menu');document.body.classList.remove('locked')}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';header.classList.toggle('menu-open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');document.body.classList.toggle('locked',open)});$$('nav a').forEach(a=>a.addEventListener('click',closeMenu));addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
$$('dialog').forEach(d=>{d.querySelector('.close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
function contact(kind){if(CONTACT[kind]){window.open(CONTACT[kind],'_blank','noopener,noreferrer');return}$('#contact-message').textContent=kind==='instagram'?'O perfil oficial do Instagram será conectado a esta demonstração em breve.':'Esta é uma demonstração. O canal de contato da COMMO será conectado em breve.';$('#contact-dialog').showModal()}
$$('.contact-trigger').forEach(b=>b.addEventListener('click',()=>contact('whatsapp')));$$('.instagram-trigger').forEach(b=>b.addEventListener('click',()=>contact('instagram')));$('.dismiss').addEventListener('click',()=>$('#contact-dialog').close());
